server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/users/**
#          filters:
#            - AuthFilter
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/products/**
#          filters:
#            - AuthFilter
        - id: payment-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/payments/**
#          filters:
#            - AuthFilter
        - id: orders-service
          uri: http://localhost:8083
          predicates:
              - Path=/api/orders/**
      #          filters:
      #            - AuthFilter
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
