server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:

        # User-service
        - id: user-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/users/**
#          filters:
#          - AuthFilter

        # Product-service
        - id: product-service-products
          uri: http://localhost:8081
          predicates:
            - Path=/api/products/**
        - id: product-service-category
          uri: http://localhost:8081
          predicates:
            - Path=/api/categories/**
#          filters:
#          - AuthFilter

        # Payment-service
        - id: payment-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/payments/**
#          filters:
#          - AuthFilter

        # Order-service
        - id: orders-service-orders
          uri: http://localhost:8083
          predicates:
              - Path=/api/orders/**
        - id: orders-service-carts
          uri: http://localhost:8083
          predicates:
            - Path=/api/carts/**
#          filters:
#          - AuthFilter

        # Notification-service
        - id: notification-service
          uri: http://localhost:8084
          predicates:
              - Path=/api/notifications/**
#         filters:
#          - AuthFilter

        # Favourite-service
        - id: favourite-service
          uri: http://localhost:8085
          predicates:
              - Path=/api/favourites/**
#         filters:
#          - AuthFilter

        # Login, SignUp
        - id: signIn-signUp
          uri: http://localhost:8080
          predicates:
            - Path=/login/**
#         filters:
#          - AuthFilter

        # Admin
        - id: admin
          uri: http://localhost:8080
          predicates:
              - Path=/admin/**
#         filters:
#          - AuthFilter

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
